06_pjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/commnents/', views.comments_create, name='comments_create'),
    path('<int:movie_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:pk>/likes/', views.likes, name='likes'),
    path('search/', views.search, name='search'),
]

06_pjt/movies/models.py
from django.db import models
from django.conf import settings

class Movie(models.Model):
    title = models.CharField(max_length=20)
    description = models.TextField()
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie_like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_like_movies")

    def __str__(self):
        return f"__str__ : title = {self.title}"

class Comment(models.Model):
    content = models.CharField(max_length=100)
    movie_id = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

06_pjt/movies/forms.py
from django import forms
from .models import Movie, Comment


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'description')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

06_pjt/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Comment
from .forms import MovieForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_safe, require_POST, require_http_methods

@require_safe
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)

@require_http_methods(['GET','POST'])
@login_required
def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.user_id = request.user
            movie.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()
    context = {
        'form': form,
    }
    return render(request, 'movies/create.html', context)

@require_safe
def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    comments = Comment.objects.all()
    comment_form = CommentForm()
    context = {
        'movie': movie,
        'comment_form': comment_form,
        'comments': comments
    }
    return render(request, 'movies/detail.html', context)

@require_POST
@login_required
def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    movie.delete()
    return redirect('movies:index')

@require_http_methods(['GET','POST'])
@login_required
def update(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.user.pk == pk:
        if request.method == 'POST':
            form = MovieForm(request.POST, instance=movie)
            if form.is_valid():
                form.save()
                return redirect('movies:detail', movie.pk)
        else:
            form = MovieForm(instance=movie)
        context = {
            'movie': movie,
            'form': form,
        }
        return render(request, 'movies/update.html', context)
    return redirect('movies:detail', pk)

@require_POST
@login_required
def comments_create(request, pk):
    movie = Movie.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        print(movie)
        comment.movie_id = movie
        comment.user_id = request.user
        comment.save()
    return redirect('movies:detail', movie.pk)

@require_POST
@login_required
def comment_delete(request, movie_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user == comment.user_id:
        comment.delete()
    return redirect("movies:detail", movie_pk)

@require_POST
@login_required
def likes(request, pk):
    movie = Movie.objects.get(pk=pk)
    if movie.movie_like_users.filter(pk=request.user.pk).exists():
        movie.movie_like_users.remove(request.user)
    else:
        movie.movie_like_users.add(request.user)
    return redirect('movies:index')


def search(request):
    if request.method == "POST":
        searched = request.POST['searched']
        searcheds = list(searched.strip().split())
        movies = set()
        
        for searched in searcheds:
            movies.add(Movie.objects.filter(title__contains=searched))

        context = {
            'movies': list(movies)
        }
        
        return render(request, 'movies/search.html', context)

06_pjt/movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <hr>
  <form action="{% url 'movies:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
  <hr>
  <a href="{% url 'movies:index' %}">BACK</a>
{% endblock %}

06_pjt/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL</h1>
  <hr>
  <div>
    <h5>{{ movie.title }}</h5>
    <p>{{ movie.description }}</p>
    {% if user.pk == movie.user_id.pk %}
    <a href="{% url 'movies:update' movie.pk %}">수정</a>
    <a href="{% url 'movies:delete' movie.pk %}">삭제</a>
    {% endif %}
  </div>
  <a href="{% url 'movies:index' %}">BACK</a>
  <hr>
  <h4>리뷰 목록</h4>
  {% if comments %}
    <p><b>{{ comments|length }}개의 리뷰가 있습니다.</b></p>
  {% endif %}
  <ul>
    {% for comment in comments %}
      <li>
        {{ comment.user_id }} - {{ comment.content }}
        {% if user == comment.user_id %}
          <form action="{% url 'movies:comment_delete' movie.pk comment.pk %}" method="POST" class="d-inline">
            {% csrf_token %}
            <input type="submit" value="삭제" class="btn btn-danger btn-sm">
          </form>
        {% endif %}
      </li>
    {% empty %}
      <li>리뷰가 없어요..!</li>
    {% endfor %}
  </ul>

  <hr>
  {% if request.user.is_authenticated %}
    <form action="{% url 'movies:comments_create' movie.pk %}" method="POST">
      {% csrf_token %}
      {{comment_form.as_p}}
      <input type="submit" value="작성" class="btn btn-primary btn-sm">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}" class="btn btn-success btn-sm">리뷰를 작성하려면 로그인하세요.</a>
  {% endif %}
{% endblock  %}

06_pjt/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX</h1>
  {% if user.is_authenticated %}
  <a href="{% url 'movies:create' %}">[CREATE]</a>
  {% else %}
  <a href="{% url 'accounts:login' %}">[CREATE]</a>
  {% endif %}
  <hr>
  {% for movie in movies %}
    <h1>영화 제목 : <a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a></h1>
    
    <p>
      작성자 : <a href="{% url 'accounts:profile' movie.user_id %}">{{movie.user_id}}</a>
    </p>
    <br>
    <div>
    {% if user.is_authenticated %}
    <form action="{% url 'movies:likes' movie.pk %}" method="post">
      {% csrf_token %}
      {% if user in movie.movie_like_users.all %}
        <input type="submit" value="좋아요 취소" class="btn btn-primary btn-sm">
      {% else %}
        <input type="submit" value="좋아요" class="btn btn-primary btn-sm">
      {% endif %}
    </form>
    {% endif %}
    <span>{{ movie.movie_like_users.all|length }} 명이 이 글을 좋아합니다.</span>
    </div>
    <hr>
  {% endfor %}
  <form class="d-flex" method="POST" action="{% url 'movies:search' %}">
    {% csrf_token %}
    <input class="form-control me-2" type="search" placeholder="Search" name="searched" aria-label="Search">
    <button class="btn btn-outline-success" type="submit"> Search </button>
  </form>
{% endblock content %}

06_pjt/movies/templates/movies/search.html
{% extends 'base.html' %}


{% block content %}

<h1>검색결과</h1>
<hr>
{% for movie in movies %}
  {% for a in movie %}
    <h2>{{a.title}}</h2>
    <p>{{a.description}}</p>
  {% endfor %}
{% endfor %}
{% endblock content %}

06_pjt/movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <hr>
  <form action="{% url 'movies:update' movie.pk %}" method="POST">
    {% csrf_token %}
    <div>
      <label for="title">TITLE</label>
      <input type="text" id="title" name="title" value="{{ movie.title }}">
    </div>
    <div>
      <label for="description">DESCRIPTION</label>
      <textarea id="description" rows="3" name="description">{{ movie.description }}</textarea>
    </div>
    <input type="reset" value="Reset">
    <button type="submit">Submit</button>
  </form>
  <hr>
  <a href="{% url 'movies:detail' movie.pk %}">BACK</a>
{% endblock %}