05_pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login',),
    path('logout/', views.logout, name='logout',),
    path('signup/', views.signup, name='signup',),
    path('delete/', views.delete, name='delete',),
    path('update/', views.update, name='update',),
    path('password/', views.change_password, name='change_password'),
]

05_pjt/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

05_pjt/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()

class CustomerUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name')

05_pjt/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from .forms import CustomerUserChangeForm, CustomUserCreationForm
from django.views.decorators.http import require_http_methods, require_POST


# Create your views here.
@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/login.html', context)

@require_POST
def logout(request):
    auth_logout(request)
    return redirect('movies:index') 

@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/signup.html', context)

@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == "POST":
        form = CustomerUserChangeForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomerUserChangeForm(instance=request.user)
    context = {
        'form' : form,
    }
    return render(request, 'accounts/update.html', context)

@require_POST
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('movies:index')

@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form' : form,
    }
    return render(request, 'accounts/change_password.html', context)

05_pjt/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block contents %}
{% load bootstrap5 %}
<div class="w-50 mx-auto border border-grey rounded p-5 pt-3 my-5">
    <h1>비밀번호 변경</h1>
    <form action="{% url 'accounts:change_password' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
    <input class="btn btn-primary" type="submit" value="변경하기">
</form>
<hr>
<a href="{% url 'movies:index' %}">돌아가기</a>
</div>
{% endblock contents %}

05_pjt/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block contents %}
{% load bootstrap5 %}
<div class="w-50 mx-auto border border-grey rounded p-5 pt-3 my-5">
    <h1>로그인</h1>
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="d-flex justify-content-between">
            <input class="btn btn-primary" type="submit" value="로그인">
            <a class="btn btn-success" href="{% url 'accounts:signup' %}">회원가입하러 가기</a>
        </div>
    </form>
    <hr>
    <a href="{% url 'movies:index' %}">돌아가기</a>
</div>
{% endblock contents %}

05_pjt/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block contents %}
{% load bootstrap5 %}
<div class="w-50 mx-auto border border-grey rounded p-5 pt-3 my-5">
    <h1>회원가입</h1>
    <form action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="d-flex justify-content-between">
            <input class="btn btn-primary" type="submit" value="가입하기">
        </div>
    </form>
    <hr>
    <a href="{% url 'movies:index' %}">돌아가기</a>
</div>
{% endblock contents %}

05_pjt/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block contents %}
{% load bootstrap5 %}
<div class="w-50 mx-auto border border-grey rounded p-5 pt-3 my-5">
    <h1>회원정보수정</h1>
    <form action="{% url 'accounts:update' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="d-flex justify-content-between">
            <input class="btn btn-primary" type="submit" value="수정하기">
            <a class="btn btn-danger" href="{% url 'accounts:delete' %}">회원탈퇴</a>
        </div>
    </form>
    <hr>
    <a href="{% url 'movies:index' %}">돌아가기</a>
</div>
{% endblock contents %}