04_pjt/accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signout/', views.signout, name='signout'),
    path('update/', views.update, name='update'),
    path('password/', views.changepw, name='changepw'),
]

04_pjt/movies/urls.py
from django.urls import path
from . import views

app_name = "movies"
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

04_pjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

04_pjt/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

04_pjt/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=20)
    audience = models.IntegerField()
    realease_date = models.DateField()
    genre = models.CharField(max_length=30)
    score = models.FloatField()
    poster_url = models.URLField(max_length=300, blank=True)
    description = models.TextField()
    actor_image = models.ImageField(blank=True)
    
    def __str__(self):
        return f"{self.pk}번째 영화 - {self.title}"

04_pjt/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        
        
class CustomUserChangeForm(UserChangeForm):
    
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = {
            'first_name',
            'last_name',
            'email',
        }

04_pjt/movies/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    COMIC = "코미디"
    HOROR = '공포'
    ROMANCE = '로맨스'
    GENRE_CHOICES = [
        (COMIC, 'comedy'),
        (HOROR, 'horor'),
        (ROMANCE, 'romance'),
    ]
        
    genre = forms.ChoiceField(
        choices=GENRE_CHOICES,
    )
    
    score = forms.FloatField(
        widget=forms.NumberInput(
            attrs={
            'min':0,
            'max':5,
            'step':0.5
            }
        )
    )
    
    realease_date = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'type' : 'date'
            }
        )
    )

    
    
    class Meta:
        model = Movie
        fields = '__all__'

04_pjt/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from .forms import CustomUserChangeForm, CustomUserCreationForm
from .models import User
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.http import require_http_methods, require_POST, require_safe


# Create your views here.
@require_http_methods(['GET','POST'])
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request,user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET','POST'])
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    auth_logout(request)
    return redirect('movies:index')


@require_POST
def signout(request):
    request.user.delete()
    auth_logout(request)
    return redirect('movies:index')


@require_http_methods(['GET','POST'])
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, request.user)
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request,'accounts/update.html', context)


@require_http_methods(['GET','POST'])
def changepw(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, request.user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/changepw.html', context)

04_pjt/movies/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST, require_http_methods, require_safe
from .models import Movie
from .forms import MovieForm

# Create your views here.
@require_safe
def index(request):
    
    moives = Movie.objects.all()
    
    context = {
        'movies' : moives
    }
    
    return render(request, 'movies/index.html', context)


@require_http_methods(['GET','POST'])
def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = MovieForm()
    context = {
        'form':form
    }
    return render(request, 'movies/create.html',context)


@require_safe
def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    
    context = {
        'movie': movie
    }
    
    return render(request, 'movies/detail.html', context)


@require_http_methods(['GET','POST'])
def update(request,pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == "POST":
        form = MovieForm(request.POST, request.FILES, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context ={
        'form': form,
        'movie': movie,
    }
    return render(request, 'movies/update.html', context)


@require_POST
def delete(request, pk):
    Movie.objects.get(pk=pk).delete()
    return redirect('movies:index')

04_pjt/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Document</title>
    <style>
        h1 {
            text-align : center;
            margin : 20px ;
        }
    </style>
</head>
<body>
    <div class='container'>
        {% if user.is_authenticated %}
        <div class="d-flex justify-content-between">
            <h2>안녕하세요, {{user}} 님 </h2>
            <div class="d-flex my-auto">
                <form action="{% url 'accounts:logout' %}" method="POST">
                    {% csrf_token %}
                    <input class="btn btn-warning" type="submit" value="로그아웃">
                </form>
                <form class="mx-2" action="{% url 'accounts:signout' %}" method='POST'>
                    {% csrf_token %}
                    <input class="btn btn-danger" type="submit" value="회원탈퇴">
                </form>
                <a class="btn btn-info" href="{% url 'accounts:update' %}">정보수정</a>
            </div>
        </div>
        {% else %}
        <div class="my-1 text-end">
            <a class="btn btn-success" href="{% url 'accounts:signup' %}">회원가입</a>
            <a class="btn btn-dark" href="{% url 'accounts:login' %}">로그인</a>
        </div>
        {% endif %}
    <hr>
    <img class='w-100' src="{% static 'header.jpg' %}" alt="">

    {% block content %}
    {% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>